CREATE TABLE emitter_type (
    id BIGSERIAL PRIMARY KEY,
    type_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE emitter_owner (
    id BIGSERIAL PRIMARY KEY,
    owner_name VARCHAR(255) NOT NULL UNIQUE
);