spring:
  application:
    name: EmitterVerification
  
  config:
    import: optional:file:.env[.properties]
  
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${POSTGRES_DRIVER}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true