spring:
  application:
    name: EmitterVerification
  
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:5432/${POSTGRES_DATABASE:emitterverificationdb}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: ${POSTGRES_DRIVER:org.postgresql.Driver}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true

page:
  default:
    number: 1
    size: 5
    sort:
      field: id
      direction: true